services:

  nifi:
    image: apache/nifi:1.27.0
    ports:
      - 18443:8443 # Unsecured HTTP Web Port
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=Password123456
      - NIFI_WEB_HTTP_PORT=8443
    volumes:
      - ./drivers:/opt/nifi/nifi-current/drivers
      - ./shared-folder:/opt/nifi/nifi-current/ls-target
      # - ./nifi-conf:/opt/nifi/nifi-current/conf

  registry:
    image: apache/nifi-registry:1.27.0
    ports:
      - 18080:18080
    environment:
      - NIFI_REGISTRY_WEB_HTTP_PORT=18080
      
    

