services:
  # zookeeper:
  #   hostname: zookeeper
  #   container_name: zookeeper
  #   image: bitnami/zookeeper:3.7.1
  #   ports:
  #     - 2181
  #   environment:
  #     ALLOW_ANONYMOUS_LOGIN: yes
  #     ZOO_MY_ID: 1
  #     ZOO_SERVERS: server.1=zookeeper:2888:3888

  nifi:
    image: apache/nifi:1.19.0
    # depends_on:
    #   - zookeeper
    ports:
      - 18443:8443 # Unsecured HTTP Web Port
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=Password123456
      - NIFI_WEB_HTTP_PORT=8443
      # - NIFI_CLUSTER_IS_NODE=true
      # - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      # - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      # - NIFI_ELECTION_MAX_WAIT=1 min

  registry:
    image: apache/nifi-registry:1.27.0
    ports:
      - 18080:18080
    environment:
      - NIFI_REGISTRY_WEB_HTTP_PORT=18080
    

